service: url-to-image-local-main

provider:
 name: aws
 runtime: nodejs12.x
 memorySize: 128
 timeout: 10
 stage: local
 region: ap-east-1

functions:
 api:
   handler: lambda.universal
   events:
     - http: ANY {proxy+}
     - http: ANY /
